using Test

include("test_conn.jl")
include("test_pipeline.jl")
include("test_integration.jl")
include("test_changeset.jl")
include("test_web.jl")
include("test_dynamic_router.jl")
include("test_repo.jl")
include("test_repo_concurrency.jl")
include("test_web_error.jl")
include("test_migration.jl")
include("test_generator.jl")
include("test_resource.jl")
include("test_repo_crud.jl")
include("test_migration_ddl.jl")
include("test_generator_migration.jl")
include("test_behavioral.jl")