"""
    module OpenAPIModule

Geração automática de especificação OpenAPI 3.0 a partir das rotas registradas.
"""
module OpenAPIModule

using ..RouterModule
using JSON3

export generate_spec, spec_to_json, route_to_openapi_path, extract_path_params

"""
    route_to_openapi_path(path::String) :: String

Converte `:param` para `{param}` no path.
"""
function route_to_openapi_path(path::String)::String
    return replace(path, r":([a-zA-Z_][a-zA-Z0-9_]*)" => s"{\1}")
end

"""
    extract_path_params(path::String) :: Vector{String}

Extrai nomes de parâmetros do path (prefixados com :).
"""
function extract_path_params(path::String)::Vector{String}
    params = String[]
    for m in eachmatch(r":([a-zA-Z_][a-zA-Z0-9_]*)", path)
        push!(params, m.captures[1])
    end
    return params
end

"""
    build_param_object(name::String) :: Dict

Cria um objeto parameter OpenAPI para path param.
"""
function build_param_object(name::String)::Dict
    return Dict(
        "name" => name,
        "in" => "path",
        "required" => true,
        "schema" => Dict("type" => "string")
    )
end

"""
    generate_spec(router; title, version, description) :: Dict

Gera a especificação OpenAPI 3.0 como Dict a partir de um router.
"""
function generate_spec(router::RouterModule.SuindaraRouter;
    title::String="Suindara API",
    version::String="0.1.0",
    description::String="Auto-generated by Suindara.jl"
)::Dict
    paths = Dict{String, Any}()

    for route in router.routes
        openapi_path = route_to_openapi_path(route.path_template)
        method = lowercase(route.method)
        params = extract_path_params(route.path_template)

        if !haskey(paths, openapi_path)
            paths[openapi_path] = Dict{String, Any}()
        end

        operation = Dict{String, Any}(
            "summary" => "$(route.method) $(route.path_template)",
            "responses" => Dict(
                "200" => Dict("description" => "Successful response")
            )
        )

        if !isempty(params)
            operation["parameters"] = [build_param_object(p) for p in params]
        end

        paths[openapi_path][method] = operation
    end

    return Dict(
        "openapi" => "3.0.0",
        "info" => Dict(
            "title" => title,
            "version" => version,
            "description" => description
        ),
        "paths" => paths
    )
end

"""
    spec_to_json(spec::Dict) :: String

Serializa a spec para JSON.
"""
function spec_to_json(spec::Dict)::String
    return JSON3.write(spec)
end

end # module
